### ISSUE TITLE
The ruby generator doesn’t work with requesting user tokens

### ISSUE THREAD

**Issue by cbothner** [pelauimagineering/apple-music-token-generator#4]
The ruby generator doesn't work in my setup, but the python one does. Which is infuriating, because I have a ruby on rails app.

ruby 2.5 (tested with 2.4 too).
`gem "jwt", "2.1.0"` (tested with 2.0.0 too)

Python generated code: `eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiIsImtpZCI6IjdEOTlRVVpYNTgifQ.eyJpc3MiOiJaOUY3NzlRSlhBIiwiZXhwIjoxNTI5MzExMDg3LCJpYXQiOjE1MjkyNjc4ODd9.gNDrX1NUpNxLyd6CpBgrkWoSjcgCsi-TKAjYw-49EeNz-PHpEmiJfYYNDEKhOOpbWvz06atkjDVv1jiShcmqYg`
Ruby generated code: `eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImFsZyI6IkVTMjU2Iiwia2lkIjoiN0Q5OVFVWlg1OCJ9.eyJpc3MiOiJaOUY3NzlRSlhBIiwiZXhwIjoxNTI5MzExMTM1LCJpYXQiOjE1MjkyNjc5MzV9.bnAvl70qvkbz8P--YdVNcJNQnEotsd_Zg4MGDYa08iilAR0fP8SBE_IBOobZGFRWXr1DczBZj1pRVLsfq_Iglw`

Using this sample code https://github.com/HumApp/MusicKit the token generated from the ruby script gives this error
```
SSAccountStore: Failed to fetch the backing accounts. error = Error Domain=com.apple.accounts Code=9 "(null)"
An error occurred when requesting user token: The operation couldn’t be completed. (SKErrorDomain error 7.)
```
but the python one works.

I have been digging all day for this, and the best i can come up with is either ruby's encryption scheme is doing something wrong or there's something significant to the fact that https://jwt.io shows the keys in the body in different orders (even though the i have the scripts listing them in the same order). Something with the jwt gem's merging of the `:alg` key?

Anything you can do to help would be appreciated. I feel like I'm going insane.

**Comment by saru2020** [comment]
Am facing the same issue. Any updates here?

**Comment by florentmorin** [comment]
@saru2020 : Fixed by https://github.com/pelauimagineering/apple-music-token-generator/pull/5

**Comment by Shpigford** [comment]
Unfortunately @florentmorin's fix didn't work for me. Still having issues generating valid tokens with the ruby script (but able to do so fine w/ the python).

**Comment by florentmorin** [comment]
I am using Ruby 2.5.0 provided by RVM and my open-source installation is based on Homebrew. 
I am using last version of jwt gem.
It’s now in production integrated with a Ruby on Rails 5.2 app hosted by Heroku. And it works fine. 
The test is easy:
- generate token
- extract parts (separated with dots)
- extract JWT parts (header and payload) using a Base64 decoding
- verify data.
Initial version provide 2 « alg » items. Now, there is only one.
